version: '3.9'
services:
  main-db-postgres:
    container_name: 'main-db-postgres'
    restart: always
    image: 'postgres:12.9'
    volumes:
      - main-db-data:/var/lib/postgresql/data
      - ./docker/main-db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 5441:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-boiler-main-db
    networks:
      - some-net

volumes:
  rabbitmq_data:
  main-db-data:

networks:
  some-net:
    driver: bridge