{{ define "header" -}}
{{- $s := .Data -}}
-- Generated by xo for the {{ .Data.Name }} schema.
{{ end }}

{{ define "createdb" -}}
{{- $s := .Data -}}

{{- if $s.Tables }}
{{- range $t := $s.Tables }}
-- insert
-- name: Insert{{ capitalize (snakeToCamel $t.Name) }} :exec
INSERT INTO "{{ $t.Name }}" (
{{- range $i, $c := $t.Columns }}
  "{{ $c.Name }}"{{ comma $i $t.Columns }}
{{- end -}}
) VALUES (
{{- range $i, $c := $t.Columns }}
  ${{ inc $i }}{{ comma $i $t.Columns }}
{{- end -}}
);

-- insert
-- name: Insert{{ capitalize (snakeToCamel $t.Name) }}Result :execresult
INSERT INTO "{{ $t.Name }}" (
{{- range $i, $c := $t.Columns }}
  "{{ $c.Name }}"{{ comma $i $t.Columns }}
{{- end -}}
) VALUES (
{{- range $i, $c := $t.Columns }}
  ${{ inc $i }}{{ comma $i $t.Columns }}
{{- end -}}
);

-- insert
-- name: Insert{{ capitalize (snakeToCamel $t.Name) }}Returning :one
INSERT INTO "{{ $t.Name }}" (
{{- range $i, $c := $t.Columns }}
  "{{ $c.Name }}"{{ comma $i $t.Columns }}
{{- end -}}
) VALUES (
{{- range $i, $c := $t.Columns }}
  ${{ inc $i }}{{ comma $i $t.Columns }}
{{- end -}}
)
RETURNING *;

{{- range $i, $pk := $t.PrimaryKeys }}
-- delete by {{ $pk.Name }}
-- name: Delete{{ capitalize (snakeToCamel $t.Name) }}By{{ capitalize (snakeToCamel $pk.Name) }} :execresult
DELETE FROM "{{ $t.Name }}"
WHERE "{{ $pk.Name }}" = $1;
{{- end -}}

{{- range $i, $pk := $t.PrimaryKeys }}
-- select by {{ $pk.Name }}
-- name: Select{{ capitalize (snakeToCamel $t.Name) }}By{{ capitalize (snakeToCamel $pk.Name) }} :one
SELECT * FROM "{{ $t.Name }}"
WHERE "{{ $pk.Name }}" = $1;
{{- end -}}

-- upsert
-- name: Upsert{{ capitalize (snakeToCamel $t.Name) }} :execresult
INSERT INTO "{{ $t.Name }}" (
{{- range $i, $c := $t.Columns }}
  "{{ $c.Name }}"{{ comma $i $t.Columns }}
{{- end -}}
) VALUES (
{{- range $i, $c := $t.Columns }}
  ${{ inc $i }}{{ comma $i $t.Columns }}
{{- end -}}
) ON CONFLICT (id) DO
UPDATE SET {{- range $i, $c := $t.Columns }}
  "{{ $c.Name }}" = EXCLUDED."{{ $c.Name }}"{{ comma $i $t.Columns }}
{{- end -}};


{{ end -}}
{{- end -}}
{{ end -}}
