package maindb

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/Dionid/go-boiler/pkg/qbik"
)

type GooseDbVersionTableSt struct {
	qbik.Table
	ID        qbik.Column[int]
	VersionID qbik.Column[int64]
	IsApplied qbik.Column[bool]
	Tstamp    qbik.Column[sql.NullTime]
}

func (t GooseDbVersionTableSt) As(alias string) GooseDbVersionTableSt {
	t.Table.TableAlias = fmt.Sprintf(`"%s"`, alias)
	t.ID = qbik.NewColumnWithAlias[int](t.Table, t.ID.ColumnName, t.ID.ColumnAlias)
	t.VersionID = qbik.NewColumnWithAlias[int64](t.Table, t.VersionID.ColumnName, t.VersionID.ColumnAlias)
	t.IsApplied = qbik.NewColumnWithAlias[bool](t.Table, t.IsApplied.ColumnName, t.IsApplied.ColumnAlias)
	t.Tstamp = qbik.NewColumnWithAlias[sql.NullTime](t.Table, t.Tstamp.ColumnName, t.Tstamp.ColumnAlias)

	return t
}

var GooseDbVersionTableBase = qbik.Table{
	TableName:  `"goose_db_version"`,
	TableAlias: `"goose_db_version"`,
}

var GooseDbVersionTable = GooseDbVersionTableSt{
	Table:     GooseDbVersionTableBase,
	ID:        qbik.NewColumn[int](GooseDbVersionTableBase, `"id"`),
	VersionID: qbik.NewColumn[int64](GooseDbVersionTableBase, `"version_id"`),
	IsApplied: qbik.NewColumn[bool](GooseDbVersionTableBase, `"is_applied"`),
	Tstamp:    qbik.NewColumn[sql.NullTime](GooseDbVersionTableBase, `"tstamp"`),
}

// # Constants

type (
	GooseDbVersionIDCT        = int
	GooseDbVersionVersionIDCT = int64
	GooseDbVersionIsAppliedCT = bool
	GooseDbVersionTstampCT    = sql.NullTime
)

const (
	GooseDbVersionIDCN        = `"id"`
	GooseDbVersionVersionIDCN = `"version_id"`
	GooseDbVersionIsAppliedCN = `"is_applied"`
	GooseDbVersionTstampCN    = `"tstamp"`
)

// # Model

type GooseDbVersionModel struct {
	ID        int          `json:"id" db:"id"`
	VersionID int64        `json:"version_id" db:"version_id"`
	IsApplied bool         `json:"is_applied" db:"is_applied"`
	Tstamp    sql.NullTime `json:"tstamp" db:"tstamp"`
}

func NewGooseDbVersionModel(
	ID int,
	VersionID int64,
	IsApplied bool,
	Tstamp sql.NullTime,
) *GooseDbVersionModel {
	return &GooseDbVersionModel{
		ID:        ID,
		VersionID: VersionID,
		IsApplied: IsApplied,
		Tstamp:    Tstamp,
	}
}

// ## Insertable

type InsertableGooseDbVersionModel struct {
	VersionID int64        `json:"version_id" db:"version_id"`
	IsApplied bool         `json:"is_applied" db:"is_applied"`
	Tstamp    sql.NullTime `json:"tstamp" db:"tstamp"`
}

func NewInsertableGooseDbVersionModel(
	VersionID int64,
	IsApplied bool,
	Tstamp sql.NullTime,
) *InsertableGooseDbVersionModel {
	return &InsertableGooseDbVersionModel{
		VersionID: VersionID,
		IsApplied: IsApplied,
		Tstamp:    Tstamp,
	}
}

func InsertIntoGooseDbVersionTable(
	ctx context.Context,
	db DB,
	modelsList ...*InsertableGooseDbVersionModel,
) (sql.Result, error) {
	if modelsList == nil {
		return nil, errors.New("InsertableGooseDbVersionModel is nil")
	}

	valueSetList := make([]qbik.ValuesSetSt, len(modelsList))

	for i, model := range modelsList {
		if model == nil {
			return nil, errors.New("InsertableUserModel is nil")
		}

		valueSetList[i] = qbik.ValueSet(
			qbik.VALUE(GooseDbVersionTable.VersionID, model.VersionID),
			qbik.VALUE(GooseDbVersionTable.IsApplied, model.IsApplied),
			qbik.VALUE(GooseDbVersionTable.Tstamp, model.Tstamp),
		)
	}

	query, err := qbik.Query(
		qbik.INSERT_INTO(
			GooseDbVersionTable,
			GooseDbVersionTable.VersionID,
			GooseDbVersionTable.IsApplied,
			GooseDbVersionTable.Tstamp,
		),
		qbik.VALUES(
			valueSetList...,
		),
	)
	if err != nil {
		return nil, err
	}

	return db.ExecContext(ctx, query.SQL, query.Args...)
}

func InsertIntoGooseDbVersionTableReturningAll(
	ctx context.Context,
	db DB,
	modelsList ...*InsertableGooseDbVersionModel,
) (*GooseDbVersionModel, error) {
	if modelsList == nil {
		return nil, errors.New("InsertableGooseDbVersionModel is nil")
	}

	valueSetList := make([]qbik.ValuesSetSt, len(modelsList))

	for i, model := range modelsList {
		if model == nil {
			return nil, errors.New("InsertableUserModel is nil")
		}

		valueSetList[i] = qbik.ValueSet(
			qbik.VALUE(GooseDbVersionTable.VersionID, model.VersionID),
			qbik.VALUE(GooseDbVersionTable.IsApplied, model.IsApplied),
			qbik.VALUE(GooseDbVersionTable.Tstamp, model.Tstamp),
		)
	}

	query, err := qbik.Query(
		qbik.INSERT_INTO(
			GooseDbVersionTable,
			GooseDbVersionTable.VersionID,
			GooseDbVersionTable.IsApplied,
			GooseDbVersionTable.Tstamp,
		),
		qbik.VALUES(
			valueSetList...,
		),
		qbik.RETURNING(GooseDbVersionTable.AllColumns()),
	)
	if err != nil {
		return nil, err
	}

	row := db.QueryRowxContext(ctx, query.SQL, query.Args...)
	var model GooseDbVersionModel
	err = row.Scan(
		&model.ID,
		&model.VersionID,
		&model.IsApplied,
		&model.Tstamp,
	)
	if err != nil {
		return nil, err
	}

	return &model, nil
}

// ## Updatable

type UpdatableGooseDbVersionModel struct {
	ID        *int          `json:"id" db:"id"`
	VersionID *int64        `json:"version_id" db:"version_id"`
	IsApplied *bool         `json:"is_applied" db:"is_applied"`
	Tstamp    *sql.NullTime `json:"tstamp" db:"tstamp"`
}

func NewUpdatableGooseDbVersionModel(
	ID *int,
	VersionID *int64,
	IsApplied *bool,
	Tstamp *sql.NullTime,
) *UpdatableGooseDbVersionModel {
	return &UpdatableGooseDbVersionModel{
		ID,
		VersionID,
		IsApplied,
		Tstamp,
	}
}

// ## Select by ID
func SelectGooseDbVersionTableByID(
	ctx context.Context,
	db DB,
	ID int,
) (*GooseDbVersionModel, error) {
	query, err := qbik.Query(
		qbik.SELECT(
			GooseDbVersionTable.AllColumns(),
		),
		qbik.FROM(GooseDbVersionTable),
		qbik.WHERE(
			qbik.EQUAL(GooseDbVersionTable.ID, ID),
		),
		qbik.LIMIT(1),
	)
	if err != nil {
		return nil, err
	}

	row := db.QueryRowxContext(ctx, query.SQL, query.Args...)
	model := &GooseDbVersionModel{}
	err = row.Scan(
		&model.ID,
		&model.VersionID,
		&model.IsApplied,
		&model.Tstamp,
	)
	if err != nil {
		return nil, err
	}

	return model, nil
}

// ## Delete by ID
func DeleteFromGooseDbVersionTableByID(
	ctx context.Context,
	db DB,
	ID int,
) (sql.Result, error) {
	query, err := qbik.Query(
		qbik.DELETE_FROM(
			GooseDbVersionTable,
		),
		qbik.WHERE(
			qbik.EQUAL(GooseDbVersionTable.ID, ID),
		),
	)
	if err != nil {
		return nil, err
	}

	return db.ExecContext(ctx, query.SQL, query.Args...)
}

func InsertIntoGooseDbVersionTableReturningID(
	ctx context.Context,
	db DB,
	modelsList ...*InsertableGooseDbVersionModel,
) (*int, error) {
	if modelsList == nil {
		return nil, errors.New("InsertIntoGooseDbVersionTableReturningIDResult is nil")
	}

	valueSetList := make([]qbik.ValuesSetSt, len(modelsList))

	for i, model := range modelsList {
		if model == nil {
			return nil, errors.New("InsertableUserModel is nil")
		}

		valueSetList[i] = qbik.ValueSet(
			qbik.VALUE(GooseDbVersionTable.VersionID, model.VersionID),
			qbik.VALUE(GooseDbVersionTable.IsApplied, model.IsApplied),
			qbik.VALUE(GooseDbVersionTable.Tstamp, model.Tstamp),
		)
	}

	query, err := qbik.Query(
		qbik.INSERT_INTO(
			GooseDbVersionTable,
			GooseDbVersionTable.VersionID,
			GooseDbVersionTable.IsApplied,
			GooseDbVersionTable.Tstamp,
		),
		qbik.VALUES(
			valueSetList...,
		),
		qbik.RETURNING(
			GooseDbVersionTable.ID,
		),
	)
	if err != nil {
		return nil, err
	}

	row := db.QueryRowxContext(ctx, query.SQL, query.Args...)
	var returning int
	err = row.Scan(&returning)
	if err != nil {
		return nil, err
	}

	return &returning, nil
}

// # Update
// ## Update by ID
func UpdateGooseDbVersionTableByID(
	ctx context.Context,
	db DB,
	updatableModel *UpdatableGooseDbVersionModel,
	ID int,
) (sql.Result, error) {
	valuesSetList := []qbik.Statement{}

	if updatableModel.ID != nil {
		valuesSetList = append(valuesSetList, qbik.SET_VALUE(GooseDbVersionTable.ID, *updatableModel.ID))
	}
	if updatableModel.VersionID != nil {
		valuesSetList = append(valuesSetList, qbik.SET_VALUE(GooseDbVersionTable.VersionID, *updatableModel.VersionID))
	}
	if updatableModel.IsApplied != nil {
		valuesSetList = append(valuesSetList, qbik.SET_VALUE(GooseDbVersionTable.IsApplied, *updatableModel.IsApplied))
	}
	if updatableModel.Tstamp != nil {
		valuesSetList = append(valuesSetList, qbik.SET_VALUE(GooseDbVersionTable.Tstamp, *updatableModel.Tstamp))
	}

	query, err := qbik.Query(
		qbik.UPDATE(
			GooseDbVersionTable,
		),
		qbik.SET(
			valuesSetList...,
		),
		qbik.WHERE(
			qbik.EQUAL(GooseDbVersionTable.ID, ID),
		),
	)
	if err != nil {
		return nil, err
	}

	return db.ExecContext(ctx, query.SQL, query.Args...)
}
