// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package maindb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type GooseDbVersion struct {
	ID        int32        `db:"id" json:"id"`
	VersionID int64        `db:"version_id" json:"versionId"`
	IsApplied bool         `db:"is_applied" json:"isApplied"`
	Tstamp    sql.NullTime `db:"tstamp" json:"tstamp"`
}

type User struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	Email     string       `db:"email" json:"email"`
	Password  string       `db:"password" json:"password"`
	CreatedAt time.Time    `db:"created_at" json:"createdAt"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updatedAt"`
	Role      string       `db:"role" json:"role"`
}
