// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package maindb

import (
	"context"
)

type Querier interface {
	SignInGetUser(ctx context.Context, email string) (*SignInGetUserRow, error)
}

var _ Querier = (*Queries)(nil)
