package maindb

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/Dionid/go-boiler/pkg/dioq"
	"github.com/google/uuid"
)

type UserTableSt struct {
	dioq.Table
	ID        dioq.Column[uuid.UUID]
	Name      dioq.Column[string]
	Email     dioq.Column[string]
	Password  dioq.Column[string]
	CreatedAt dioq.Column[time.Time]
	UpdatedAt dioq.Column[sql.NullTime]
	Role      dioq.Column[string]
}

func (t UserTableSt) As(alias string) UserTableSt {
	t.Table.TableAlias = fmt.Sprintf(`"%s"`, alias)
	t.ID = dioq.NewColumnWithAlias[uuid.UUID](t.Table, t.ID.ColumnName, t.ID.ColumnAlias)
	t.Name = dioq.NewColumnWithAlias[string](t.Table, t.Name.ColumnName, t.Name.ColumnAlias)
	t.Email = dioq.NewColumnWithAlias[string](t.Table, t.Email.ColumnName, t.Email.ColumnAlias)
	t.Password = dioq.NewColumnWithAlias[string](t.Table, t.Password.ColumnName, t.Password.ColumnAlias)
	t.CreatedAt = dioq.NewColumnWithAlias[time.Time](t.Table, t.CreatedAt.ColumnName, t.CreatedAt.ColumnAlias)
	t.UpdatedAt = dioq.NewColumnWithAlias[sql.NullTime](t.Table, t.UpdatedAt.ColumnName, t.UpdatedAt.ColumnAlias)
	t.Role = dioq.NewColumnWithAlias[string](t.Table, t.Role.ColumnName, t.Role.ColumnAlias)

	return t
}

var UserTableBase = dioq.Table{
	TableName:  `"user"`,
	TableAlias: `"user"`,
}

var UserTable = UserTableSt{
	Table:     UserTableBase,
	ID:        dioq.NewColumn[uuid.UUID](UserTableBase, `"id"`),
	Name:      dioq.NewColumn[string](UserTableBase, `"name"`),
	Email:     dioq.NewColumn[string](UserTableBase, `"email"`),
	Password:  dioq.NewColumn[string](UserTableBase, `"password"`),
	CreatedAt: dioq.NewColumn[time.Time](UserTableBase, `"created_at"`),
	UpdatedAt: dioq.NewColumn[sql.NullTime](UserTableBase, `"updated_at"`),
	Role:      dioq.NewColumn[string](UserTableBase, `"role"`),
}

// # Constants

type (
	UserIDCT        = uuid.UUID
	UserNameCT      = string
	UserEmailCT     = string
	UserPasswordCT  = string
	UserCreatedAtCT = time.Time
	UserUpdatedAtCT = sql.NullTime
	UserRoleCT      = string
)

const (
	UserIDCN        = `"id"`
	UserNameCN      = `"name"`
	UserEmailCN     = `"email"`
	UserPasswordCN  = `"password"`
	UserCreatedAtCN = `"created_at"`
	UserUpdatedAtCN = `"updated_at"`
	UserRoleCN      = `"role"`
)

// # Model

type UserModel struct {
	ID        uuid.UUID    `json:"id" db:"id"`
	Name      string       `json:"name" db:"name"`
	Email     string       `json:"email" db:"email"`
	Password  string       `json:"password" db:"password"`
	CreatedAt time.Time    `json:"created_at" db:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at" db:"updated_at"`
	Role      string       `json:"role" db:"role"`
}

func NewUserModel(
	ID uuid.UUID,
	Name string,
	Email string,
	Password string,
	CreatedAt time.Time,
	UpdatedAt sql.NullTime,
	Role string,
) *UserModel {
	return &UserModel{
		ID:        ID,
		Name:      Name,
		Email:     Email,
		Password:  Password,
		CreatedAt: CreatedAt,
		UpdatedAt: UpdatedAt,
		Role:      Role,
	}
}

// ## Insertable

type InsertableUserModel struct {
	ID        uuid.UUID    `json:"id" db:"id"`
	Name      string       `json:"name" db:"name"`
	Email     string       `json:"email" db:"email"`
	Password  string       `json:"password" db:"password"`
	CreatedAt time.Time    `json:"created_at" db:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at" db:"updated_at"`
	Role      string       `json:"role" db:"role"`
}

func NewInsertableUserModel(
	ID uuid.UUID,
	Name string,
	Email string,
	Password string,
	CreatedAt time.Time,
	UpdatedAt sql.NullTime,
	Role string,
) *InsertableUserModel {
	return &InsertableUserModel{
		ID:        ID,
		Name:      Name,
		Email:     Email,
		Password:  Password,
		CreatedAt: CreatedAt,
		UpdatedAt: UpdatedAt,
		Role:      Role,
	}
}

func InsertIntoUserTable(
	ctx context.Context,
	db DB,
	modelsList ...*InsertableUserModel,
) (sql.Result, error) {
	if modelsList == nil {
		return nil, errors.New("InsertableUserModel is nil")
	}

	valueSetList := make([]dioq.ValuesSetSt, len(modelsList))

	for i, model := range modelsList {
		if model == nil {
			return nil, errors.New("InsertableUserModel is nil")
		}

		valueSetList[i] = dioq.ValueSet(
			dioq.VALUE(UserTable.ID, model.ID),
			dioq.VALUE(UserTable.Name, model.Name),
			dioq.VALUE(UserTable.Email, model.Email),
			dioq.VALUE(UserTable.Password, model.Password),
			dioq.VALUE(UserTable.CreatedAt, model.CreatedAt),
			dioq.VALUE(UserTable.UpdatedAt, model.UpdatedAt),
			dioq.VALUE(UserTable.Role, model.Role),
		)
	}

	query, err := dioq.Query(
		dioq.INSERT_INTO(
			UserTable,
			UserTable.ID,
			UserTable.Name,
			UserTable.Email,
			UserTable.Password,
			UserTable.CreatedAt,
			UserTable.UpdatedAt,
			UserTable.Role,
		),
		dioq.VALUES(
			valueSetList...,
		),
	)
	if err != nil {
		return nil, err
	}

	return db.ExecContext(ctx, query.SQL, query.Args...)
}

func InsertIntoUserTableReturningAll(
	ctx context.Context,
	db DB,
	modelsList ...*InsertableUserModel,
) (*UserModel, error) {
	if modelsList == nil {
		return nil, errors.New("InsertableUserModel is nil")
	}

	valueSetList := make([]dioq.ValuesSetSt, len(modelsList))

	for i, model := range modelsList {
		if model == nil {
			return nil, errors.New("InsertableUserModel is nil")
		}

		valueSetList[i] = dioq.ValueSet(
			dioq.VALUE(UserTable.ID, model.ID),
			dioq.VALUE(UserTable.Name, model.Name),
			dioq.VALUE(UserTable.Email, model.Email),
			dioq.VALUE(UserTable.Password, model.Password),
			dioq.VALUE(UserTable.CreatedAt, model.CreatedAt),
			dioq.VALUE(UserTable.UpdatedAt, model.UpdatedAt),
			dioq.VALUE(UserTable.Role, model.Role),
		)
	}

	query, err := dioq.Query(
		dioq.INSERT_INTO(
			UserTable,
			UserTable.ID,
			UserTable.Name,
			UserTable.Email,
			UserTable.Password,
			UserTable.CreatedAt,
			UserTable.UpdatedAt,
			UserTable.Role,
		),
		dioq.VALUES(
			valueSetList...,
		),
		dioq.RETURNING(UserTable.AllColumns()),
	)
	if err != nil {
		return nil, err
	}

	row := db.QueryRowxContext(ctx, query.SQL, query.Args...)
	var model UserModel
	err = row.Scan(
		&model.ID,
		&model.Name,
		&model.Email,
		&model.Password,
		&model.CreatedAt,
		&model.UpdatedAt,
		&model.Role,
	)
	if err != nil {
		return nil, err
	}

	return &model, nil
}

// ## Updatable

type UpdatableUserModel struct {
	ID        *uuid.UUID    `json:"id" db:"id"`
	Name      *string       `json:"name" db:"name"`
	Email     *string       `json:"email" db:"email"`
	Password  *string       `json:"password" db:"password"`
	CreatedAt *time.Time    `json:"created_at" db:"created_at"`
	UpdatedAt *sql.NullTime `json:"updated_at" db:"updated_at"`
	Role      *string       `json:"role" db:"role"`
}

func NewUpdatableUserModel(
	ID *uuid.UUID,
	Name *string,
	Email *string,
	Password *string,
	CreatedAt *time.Time,
	UpdatedAt *sql.NullTime,
	Role *string,
) *UpdatableUserModel {
	return &UpdatableUserModel{
		ID,
		Name,
		Email,
		Password,
		CreatedAt,
		UpdatedAt,
		Role,
	}
}

// ## Select by Email
func SelectUserTableByEmail(
	ctx context.Context,
	db DB,
	Email string,
) (*UserModel, error) {
	query, err := dioq.Query(
		dioq.SELECT(
			UserTable.AllColumns(),
		),
		dioq.FROM(UserTable),
		dioq.WHERE(
			dioq.EQUAL(UserTable.Email, Email),
		),
		dioq.LIMIT(1),
	)
	if err != nil {
		return nil, err
	}

	row := db.QueryRowxContext(ctx, query.SQL, query.Args...)
	model := &UserModel{}
	err = row.Scan(
		&model.ID,
		&model.Name,
		&model.Email,
		&model.Password,
		&model.CreatedAt,
		&model.UpdatedAt,
		&model.Role,
	)
	if err != nil {
		return nil, err
	}

	return model, nil
}

// ## Delete by Email
func DeleteFromUserTableByEmail(
	ctx context.Context,
	db DB,
	Email string,
) (sql.Result, error) {
	query, err := dioq.Query(
		dioq.DELETE_FROM(
			UserTable,
		),
		dioq.WHERE(
			dioq.EQUAL(UserTable.Email, Email),
		),
	)
	if err != nil {
		return nil, err
	}

	return db.ExecContext(ctx, query.SQL, query.Args...)
}

func InsertIntoUserTableReturningEmail(
	ctx context.Context,
	db DB,
	modelsList ...*InsertableUserModel,
) (*string, error) {
	if modelsList == nil {
		return nil, errors.New("InsertIntoUserTableReturningEmailResult is nil")
	}

	valueSetList := make([]dioq.ValuesSetSt, len(modelsList))

	for i, model := range modelsList {
		if model == nil {
			return nil, errors.New("InsertableUserModel is nil")
		}

		valueSetList[i] = dioq.ValueSet(
			dioq.VALUE(UserTable.ID, model.ID),
			dioq.VALUE(UserTable.Name, model.Name),
			dioq.VALUE(UserTable.Email, model.Email),
			dioq.VALUE(UserTable.Password, model.Password),
			dioq.VALUE(UserTable.CreatedAt, model.CreatedAt),
			dioq.VALUE(UserTable.UpdatedAt, model.UpdatedAt),
			dioq.VALUE(UserTable.Role, model.Role),
		)
	}

	query, err := dioq.Query(
		dioq.INSERT_INTO(
			UserTable,
			UserTable.ID,
			UserTable.Name,
			UserTable.Email,
			UserTable.Password,
			UserTable.CreatedAt,
			UserTable.UpdatedAt,
			UserTable.Role,
		),
		dioq.VALUES(
			valueSetList...,
		),
		dioq.RETURNING(
			UserTable.Email,
		),
	)
	if err != nil {
		return nil, err
	}

	row := db.QueryRowxContext(ctx, query.SQL, query.Args...)
	var returning string
	err = row.Scan(&returning)
	if err != nil {
		return nil, err
	}

	return &returning, nil
}

// # Update
// ## Update by Email
func UpdateUserTableByEmail(
	ctx context.Context,
	db DB,
	updatableModel *UpdatableUserModel,
	Email string,
) (sql.Result, error) {
	valuesSetList := []dioq.Statement{}

	if updatableModel.ID != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.ID, *updatableModel.ID))
	}
	if updatableModel.Name != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.Name, *updatableModel.Name))
	}
	if updatableModel.Email != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.Email, *updatableModel.Email))
	}
	if updatableModel.Password != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.Password, *updatableModel.Password))
	}
	if updatableModel.CreatedAt != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.CreatedAt, *updatableModel.CreatedAt))
	}
	if updatableModel.UpdatedAt != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.UpdatedAt, *updatableModel.UpdatedAt))
	}
	if updatableModel.Role != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.Role, *updatableModel.Role))
	}

	query, err := dioq.Query(
		dioq.UPDATE(
			UserTable,
		),
		dioq.SET(
			valuesSetList...,
		),
		dioq.WHERE(
			dioq.EQUAL(UserTable.Email, Email),
		),
	)
	if err != nil {
		return nil, err
	}

	return db.ExecContext(ctx, query.SQL, query.Args...)
}

// ## Select by ID
func SelectUserTableByID(
	ctx context.Context,
	db DB,
	ID uuid.UUID,
) (*UserModel, error) {
	query, err := dioq.Query(
		dioq.SELECT(
			UserTable.AllColumns(),
		),
		dioq.FROM(UserTable),
		dioq.WHERE(
			dioq.EQUAL(UserTable.ID, ID),
		),
		dioq.LIMIT(1),
	)
	if err != nil {
		return nil, err
	}

	row := db.QueryRowxContext(ctx, query.SQL, query.Args...)
	model := &UserModel{}
	err = row.Scan(
		&model.ID,
		&model.Name,
		&model.Email,
		&model.Password,
		&model.CreatedAt,
		&model.UpdatedAt,
		&model.Role,
	)
	if err != nil {
		return nil, err
	}

	return model, nil
}

// ## Delete by ID
func DeleteFromUserTableByID(
	ctx context.Context,
	db DB,
	ID uuid.UUID,
) (sql.Result, error) {
	query, err := dioq.Query(
		dioq.DELETE_FROM(
			UserTable,
		),
		dioq.WHERE(
			dioq.EQUAL(UserTable.ID, ID),
		),
	)
	if err != nil {
		return nil, err
	}

	return db.ExecContext(ctx, query.SQL, query.Args...)
}

func InsertIntoUserTableReturningID(
	ctx context.Context,
	db DB,
	modelsList ...*InsertableUserModel,
) (*uuid.UUID, error) {
	if modelsList == nil {
		return nil, errors.New("InsertIntoUserTableReturningIDResult is nil")
	}

	valueSetList := make([]dioq.ValuesSetSt, len(modelsList))

	for i, model := range modelsList {
		if model == nil {
			return nil, errors.New("InsertableUserModel is nil")
		}

		valueSetList[i] = dioq.ValueSet(
			dioq.VALUE(UserTable.ID, model.ID),
			dioq.VALUE(UserTable.Name, model.Name),
			dioq.VALUE(UserTable.Email, model.Email),
			dioq.VALUE(UserTable.Password, model.Password),
			dioq.VALUE(UserTable.CreatedAt, model.CreatedAt),
			dioq.VALUE(UserTable.UpdatedAt, model.UpdatedAt),
			dioq.VALUE(UserTable.Role, model.Role),
		)
	}

	query, err := dioq.Query(
		dioq.INSERT_INTO(
			UserTable,
			UserTable.ID,
			UserTable.Name,
			UserTable.Email,
			UserTable.Password,
			UserTable.CreatedAt,
			UserTable.UpdatedAt,
			UserTable.Role,
		),
		dioq.VALUES(
			valueSetList...,
		),
		dioq.RETURNING(
			UserTable.ID,
		),
	)
	if err != nil {
		return nil, err
	}

	row := db.QueryRowxContext(ctx, query.SQL, query.Args...)
	var returning uuid.UUID
	err = row.Scan(&returning)
	if err != nil {
		return nil, err
	}

	return &returning, nil
}

// # Update
// ## Update by ID
func UpdateUserTableByID(
	ctx context.Context,
	db DB,
	updatableModel *UpdatableUserModel,
	ID uuid.UUID,
) (sql.Result, error) {
	valuesSetList := []dioq.Statement{}

	if updatableModel.ID != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.ID, *updatableModel.ID))
	}
	if updatableModel.Name != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.Name, *updatableModel.Name))
	}
	if updatableModel.Email != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.Email, *updatableModel.Email))
	}
	if updatableModel.Password != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.Password, *updatableModel.Password))
	}
	if updatableModel.CreatedAt != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.CreatedAt, *updatableModel.CreatedAt))
	}
	if updatableModel.UpdatedAt != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.UpdatedAt, *updatableModel.UpdatedAt))
	}
	if updatableModel.Role != nil {
		valuesSetList = append(valuesSetList, dioq.SET_VALUE(UserTable.Role, *updatableModel.Role))
	}

	query, err := dioq.Query(
		dioq.UPDATE(
			UserTable,
		),
		dioq.SET(
			valuesSetList...,
		),
		dioq.WHERE(
			dioq.EQUAL(UserTable.ID, ID),
		),
	)
	if err != nil {
		return nil, err
	}

	return db.ExecContext(ctx, query.SQL, query.Args...)
}
